# Site settings
title: Sami Glasco
email: samiglasco@gmail.com
url: http://thefireferret.github.io
description: "My website on the interblags."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sami Glasco

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/TheDiscoBandit
  - title: github
    url: https://github.com/TheFireFerret
  - title: linkedin
    url: http://www.linkedin.com/in/samiglasco

# Build settings
markdown: kramdown
permalink: pretty
